"""baseline

Revision ID: 9f0f344bdfa5
Revises: 
Create Date: 2026-09-23 15:17:47.161820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0f344bdfa5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('last_validated', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_validations_id'), 'script_validations', ['id'], unique=False)
    op.create_index(op.f('ix_script_validations_script_name'), 'script_validations', ['script_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cloud_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('use_iam_role', sa.Boolean(), nullable=True),
    sa.Column('aws_access_key_id', sa.String(), nullable=True),
    sa.Column('aws_secret_access_key', sa.String(), nullable=True),
    sa.Column('aws_session_token', sa.String(), nullable=True),
    sa.Column('assume_role_arn', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('aws_account_id', sa.String(), nullable=True),
    sa.Column('last_verified', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_configs_id'), 'cloud_configs', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_name', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('potential_savings', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=True),
    sa.Column('assigned_to_name', sa.String(), nullable=True),
    sa.Column('assigned_by_name', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.String(), nullable=True),
    sa.Column('completed_by_name', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_configs.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_resource_id'), 'tickets', ['resource_id'], unique=False)
    op.create_index(op.f('ix_tickets_script_name'), 'tickets', ['script_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_script_name'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_resource_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_cloud_configs_id'), table_name='cloud_configs')
    op.drop_table('cloud_configs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_script_validations_script_name'), table_name='script_validations')
    op.drop_index(op.f('ix_script_validations_id'), table_name='script_validations')
    op.drop_table('script_validations')
    # ### end Alembic commands ###
